#include <cx/log.h>
#include <cx/time.h>
#include <stdio.h>

// Run all tests in a single process, to make manual testing easier

typedef struct testspec {
    const char *descr;
    const char *module;
    const char *test;
} testspec;

static const testspec tests[] = {
    { "debug: Assertions", "debugtest", "assert" },
    { "xalloc: Allocation", "cxmemtest", "alloc" },
    { "xalloc: Usable Size", "cxmemtest", "usable_size" },
    { "xalloc: Free", "cxmemtest", "free" },
    { "xalloc: Reallocation", "cxmemtest", "realloc" },
    { "closure: Basic Closure", "closuretest", "closure" },
    { "closure: Closure Chain", "closuretest", "chain" },
    { "console: Capability detection", "contest", "caps" },
    { "console: Buffered write", "contest", "write" },
    { "console: Rope write", "contest", "write_rope" },
    { "console: UTF-8 encoding", "contest", "write_utf8" },
    { "console: Recursive lock", "contest", "lock" },
    { "console: withConLock block", "contest", "lock_block" },
    { "console: Cross-thread lock stress", "contest", "lock_stress" },
    { "console: Style downgrade ladder", "contest", "style_downgrade" },
    { "console: Style attributes", "contest", "style_attrs" },
    { "console: Style with no capability", "contest", "style_none" },
    { "console: Styled write restores prior style", "contest", "style_restore" },
    { "console: Formatted write", "contest", "fmt" },
    { "console: Styled formatted write", "contest", "fmt_styled" },
    { "console: Set cursor position", "contest", "cursor_set" },
    { "console: Relative cursor move", "contest", "cursor_move" },
    { "console: Show/hide cursor", "contest", "cursor_show" },
    { "console: Save/restore cursor", "contest", "cursor_save" },
    { "console: Erase line/screen", "contest", "cursor_erase" },
    { "console: Scroll", "contest", "cursor_scroll" },
    { "console: Alternate screen", "contest", "cursor_altscreen" },
    { "console: Cursor ops with no capability", "contest", "cursor_none" },
    { "console: conGetCursor on memory stream", "contest", "cursor_getmem" },
    { "console: Escape sequence decoding", "contest", "decode_escape" },
    { "console: Input on non-input stream", "contest", "input_wrong_kind" },
    { "digest: MD5", "digesttest", "md5" },
    { "digest: SHA-1", "digesttest", "sha1" },
    { "digest: SHA-256", "digesttest", "sha256" },
    { "format: Integers", "fmttest", "int" },
    { "format: Floating Point", "fmttest", "float" },
    { "format: Objects", "fmttest", "object" },
    { "format: Pointers", "fmttest", "ptr" },
    { "format: Strings", "fmttest", "string" },
    { "format: SUID", "fmttest", "suid" },
    { "format: Array indexing", "fmttest", "array" },
    { "format: Hashtable lookup", "fmttest", "hash" },
    { "format: Keyed arguments", "fmttest", "keyed" },
    { "format: Keyed subscripting", "fmttest", "keyedsub" },
    { "format: Keyed stvlist lookup", "fmttest", "keyedstvl" },
    { "format: Keyed variant copy", "fmttest", "keyedcopy" },
    { "format: Defaults", "fmttest", "default" },
    { "format: Error handling", "fmttest", "error" },
    { "parse: Basics", "parsetest", "basic" },
    { "parse: Types", "parsetest", "types" },
    { "parse: Parse options", "parsetest", "opts" },
    { "parse: Groups", "parsetest", "group" },
    { "parse: Defaults", "parsetest", "default" },
    { "parse: Untouched destinations", "parsetest", "untouched" },
    { "parse: Resumable matching", "parsetest", "matchat" },
    { "parse: Parsable objects", "parsetest", "object" },
    { "parse: Error handling", "parsetest", "error" },
    { "log: Log Levels", "logtest", "levels" },
    { "log: Batch", "logtest", "batch" },
    { "log: Shutdown", "logtest", "shutdown" },
    { "log: Channels", "logtest", "channels" },
    { "log: Backfill", "logtest", "backfill" },
    { "log: Destinations", "logtest", "dest" },
    { "log: Channel hierarchy", "logtest", "hierarchy" },
    { "log: Built-in cx channel", "logtest", "cxchan" },
    { "log: Call sites and rate limiting", "logtest", "site" },
    { "log: Records and deferred formatting", "logtest", "record" },
    { "log: Serializers", "logtest", "serializer" },
    { "log: Text prefix omission", "logtest", "textomit" },
    { "log: Drain groups", "logtest", "groups" },
    { "log: Volume control", "logtest", "volume" },
    { "log: Boot window", "logtest", "bootwindow" },
    { "log: Boot replay", "logtest", "bootreplay" },
    { "log: Debug ring", "logtest", "debugring" },
    { "log: Context", "logtest", "ctx" },
    { "log: Console destination", "logtest", "console" },
    { "log: Console destination styling", "logtest", "console_style" },
    { "log: Wire codec", "logtest", "wire" },
    { "log: Wire segments", "logtest", "wiresegment" },
    { "log: Wire dictionary bounds", "logtest", "wiredict" },
    { "log: Record injection", "logtest", "inject" },
    { "log: Malformed wire streams", "logtest", "wirebad" },
    { "log: Forwarding", "logtest", "forward" },
    { "log: Forward spool", "logtest", "forwardspool" },
    { "log: Forwarder drain group", "logtest", "forwardgroup" },
    { "log: Forward loop prevention", "logtest", "forwardloop" },
    { "log: Forward loop prevention, async transport", "logtest", "forwardloopasync" },
    { "log: Forward boot window backfill", "logtest", "forwardboot" },
    { "log: Subscription", "logtest", "subscribe" },
    { "log: Channel catalog", "logtest", "catalog" },
    { "log: Destination filter and level changes", "logtest", "destfilter" },
    { "object: Interface", "objtest", "iface" },
    { "object: Class Inheritance", "objtest", "inherit" },
    { "object: Interface Inheritance", "objtest", "ifinherit" },
    { "object: Override", "objtest", "override" },
    { "object: Abstract Class", "objtest", "abstract" },
    { "object: Static Cast", "objtest", "cast" },
    { "object: Dynamic Cast", "objtest", "dyncast" },
    { "object: Object Array", "objtest", "obj_array" },
    { "object: Weak References", "objtest", "weakref" },
    { "object: ClassSet", "objtest", "classset" },
    { "struct: Type Identity", "structtest", "typeidentity" },
    { "struct: Type Nesting", "structtest", "typenesting" },
    { "struct: Init/Destroy", "structtest", "initdestroy" },
    { "struct: Copy", "structtest", "copy" },
    { "struct: Nested", "structtest", "nested" },
    { "struct: Fixed Arrays", "structtest", "fixedarray" },
    { "struct: Struct Pointers", "structtest", "structp" },
    { "struct: StructSet", "structtest", "structset" },
    { "serialize: Scalars", "sertest", "scalars" },
    { "serialize: String", "sertest", "string" },
    { "serialize: SUID", "sertest", "suid" },
    { "serialize: Buffer", "sertest", "buffer" },
    { "serialize: Array", "sertest", "array" },
    { "serialize: Hashtable", "sertest", "hashtable" },
    { "serialize: Non-String Keys", "sertest", "intkeys" },
    { "serialize: Struct", "sertest", "struct" },
    { "serialize: Struct Pointers", "sertest", "structp" },
    { "serialize: Null Struct Pointers", "sertest", "structpnull" },
    { "serialize: Dynamic Struct Pointers", "sertest", "structpdyn" },
    { "serialize: Struct Set Bounds", "sertest", "structpbounds" },
    { "serialize: Nested", "sertest", "nested" },
    { "serialize: Fixed Arrays", "sertest", "fixedarray" },
    { "serialize: Overwrite", "sertest", "overwrite" },
    { "serialize: Errors", "sertest", "errors" },
    { "serialize: Unknown Members", "sertest", "unknown" },
    { "serialize: Schema", "sertest", "schema" },
    { "serialize: Generated Schemas", "sertest", "generated" },
    { "serialize: Type Resolution", "sertest", "resolve" },
    { "serialize: JSON", "sertest", "json" },
    { "serialize: JSON Nesting", "sertest", "jsonnested" },
    { "serialize: JSON Numbers", "sertest", "jsonnum" },
    { "serialize: JSON Defaults", "sertest", "jsondef" },
    { "serialize: JSON Errors", "sertest", "jsonerrors" },
    { "serialize: Binary", "sertest", "binary" },
    { "serialize: Binary Nesting", "sertest", "binnested" },
    { "serialize: Binary Numbers", "sertest", "binnum" },
    { "serialize: Binary Defaults", "sertest", "bindef" },
    { "serialize: Binary Errors", "sertest", "binerrors" },
    { "serialize: Cross Format", "sertest", "cross" },
    { "serialize: Classes", "sertest", "class" },
    { "serialize: Class Chain Gap", "sertest", "classgap" },
    { "serialize: Class Polymorphism", "sertest", "classpoly" },
    { "serialize: Serializable Classes", "sertest", "classcustom" },
    { "serialize: Class Sets", "sertest", "classset" },
    { "serialize: Class Set Bounds", "sertest", "classsetbounds" },
    { "serialize: Class Cycles", "sertest", "classcycle" },
    { "serialize: Classes in SSD", "sertest", "classssd" },
    { "serialize: Renamed members", "sertest", "rename" },
    { "serialize: Object references", "sertest", "refs" },
    { "serialize: Reference cycles", "sertest", "refcycle" },
    { "serialize: Wrapped reference ids", "sertest", "refwrap" },
    { "serialize: Reference errors", "sertest", "referrors" },
    { "serialize: Variants", "sertest", "stvar" },
    { "serialize: Variant errors", "sertest", "stvarerr" },
    { "sarray: Int Array", "sarraytest", "int" },
    { "sarray: Sorted Int Array", "sarraytest", "sorted_int" },
    { "sarray: Opaque Struct Array", "sarraytest", "opaque" },
    { "sarray: String Array", "sarraytest", "string" },
    { "sarray: Sort", "sarraytest", "sort" },
    { "sarray: String Sort", "sarraytest", "string_sort" },
    { "sarray: Custom Sort", "sarraytest", "custom_sort" },
    { "sarray: stvar Consume", "sarraytest", "stvar_consume" },
    { "string: Join", "strtest", "join" },
    { "string: Append/Prepend", "strtest", "append" },
    { "string: Substrings", "strtest", "substr" },
    { "string: Compare", "strtest", "compare" },
    { "string: Compare Length-Free", "strtest", "comparelen0" },
    { "string: Long Strings", "strtest", "longstring" },
    { "string: Find", "strtest", "find" },
    { "string: Ropes", "strtest", "rope" },
    { "string: Numeric Conversions", "strtest", "num" },
    { "string: Bytes", "strtest", "bytes" },
    { "string: Find Characters", "strtest", "findchar" },
    { "string: Trim", "strtest", "trim" },
    { "string: Replace", "strtest", "replace" },
    { "string: Split Variants", "strtest", "splitvar" },
    { "string: Hex", "strtest", "hex" },
    { "string: UTF-8", "strtest", "utf8" },
    { "string: Literals", "strtest", "literal" },
    { "strscan: Literals", "strscantest", "literal" },
    { "strscan: Extraction", "strscantest", "extract" },
    { "strscan: Typed Values", "strscantest", "typed" },
    { "strscan: Backtracking", "strscantest", "backtrack" },
    { "hashtable: Init", "httest", "init" },
    { "hashtable: Insert", "httest", "insert" },
    { "hashtable: Find", "httest", "find" },
    { "hashtable: Element Access", "httest", "htelem" },
    { "hashtable: Remove", "httest", "remove" },
    { "hashtable: Iterator", "httest", "iterator" },
    { "hashtable: Order", "httest", "order" },
    { "hashtable: Complex", "httest", "complex" },
    { "convert: Numeric Types", "converttest", "numeric" },
    { "convert: Strings", "converttest", "string" },
    { "convert: Objects", "converttest", "object" },
    { "stvar: SUID ownership", "stvartest", "suid" },
    { "stvar: Opaque ownership", "stvartest", "opaque" },
    { "stvar: Transient", "stvartest", "transient" },
    { "stvar: SSD round-trip", "stvartest", "ssd_roundtrip" },
    { "stvar: Nested", "stvartest", "nested" },
    { "thread: Basic multithreading", "thrtest", "basic" },
    { "thread: Futex", "thrtest", "futex" },
    { "thread: Futex with timeout", "thrtest", "timeout" },
    { "thread: Semaphore", "thrtest", "sema" },
    { "thread: Mutex", "thrtest", "mutex" },
    { "thread: Reader/writer lock", "thrtest", "rwlock" },
    { "thread: Event", "thrtest", "event" },
    { "thread: Event (with spin)", "thrtest", "event_s" },
    { "thread: Condition Variable", "thrtest", "condvar" },
    { "thread: 64-bit atomics", "thrtest", "atomic64" },
    { "thread: 64-bit atomics (contention)", "thrtest", "atomic64_mt" },
    { "meta: Block Wrapping", "metatest", "wrap" },
    { "meta: Protected Blocks", "metatest", "protect" },
    { "meta: Basic Try/Catch", "metatest", "ptry" },
    { "meta: Unhandled Exceptions", "metatest", "unhandled" },
    { "meta: Rethrow", "metatest", "rethrow" },
    { "meta: Cross-function Exception Handling", "metatest", "xfunc" },
    { "ssd: Semi-structured data tree", "ssdtest", "tree" },
    { "ssd: Single value root", "ssdtest", "single" },
    { "ssd: Subtrees", "ssdtest", "subtree" },
    { "ssd: Arrays", "ssdtest", "array" },
    { "buffer: Create", "buftest", "create" },
    { "buffer: Resize", "buftest", "resize" },
    { "buffer: Append", "buftest", "append" },
    { "bufchain: Basic Operations", "buftest", "chain_basic" },
    { "bufchain: Peek", "buftest", "chain_peek" },
    { "bufchain: Skip", "buftest", "chain_skip" },
    { "bufchain: Zero-Copy Read", "buftest", "chain_zerocopy_read" },
    { "bufchain: Zero-Copy Write", "buftest", "chain_zerocopy_write" },
    { "bufchain: Multi-Segment Operations", "buftest", "chain_multisegment" },
    { "bufring: Basic Operations", "buftest", "ring_basic" },
    { "bufring: Peek", "buftest", "ring_peek" },
    { "bufring: Skip", "buftest", "ring_skip" },
    { "bufring: Zero-Copy Read", "buftest", "ring_zerocopy_read" },
    { "bufring: Zero-Copy Write", "buftest", "ring_zerocopy_write" },
    { "bufring: Ring Buffer Wraparound", "buftest", "ring_wraparound" },
    { "bufring: Multi-Segment Operations", "buftest", "ring_multisegment" },
    { "bufring: Reserve/Commit", "buftest", "ring_reserve" },
    { "bufring: Reserve Across Read", "buftest", "ring_reserve_read" },
    { "bufchain: Gather IOV", "buftest", "chain_gather_iov" },
    { "bufpool: Basic Operations", "buftest", "bufpool_basic" },
    { "bufpool: Reuse", "buftest", "bufpool_reuse" },
    { "streambuffer: Push", "sbtest", "push" },
    { "streambuffer: Direct Push", "sbtest", "direct" },
    { "streambuffer: Pull", "sbtest", "pull" },
    { "streambuffer: Peek-ahead", "sbtest", "peek" },
    { "streambuffer: String Adapter", "sbtest", "string" },
    { "streambuffer: Buffer Adapter", "sbtest", "buffer" },
    { "streambuffer: Console Adapter", "sbtest", "console" },
    { "streambuffer: Producer Handoff", "sbtest", "phandoff" },
    { "streambuffer: Consumer Handoff", "sbtest", "chandoff" },
    { "streambuffer: Consumer Swap", "sbtest", "cswap" },
    { "streambuffer: Error Recovery", "sbtest", "error" },
    { "streambuffer: End With Pull Producer", "sbtest", "endpull" },
    { "streambuffer: Synchronous Flush", "sbtest", "flush" },
    { "streambuffer: Stream Reuse", "sbtest", "reuse" },
    { "streambuffer: Threaded Handoff", "sbtest", "threaded" },
    { "lineparse: Explicit EOL", "lineparsetest", "explicit" },
    { "lineparse: Auto EOL", "lineparsetest", "auto" },
    { "lineparse: Mixed EOL", "lineparsetest", "mixed" },
    { "lineparse: Push Mode", "lineparsetest", "push" },
    { "json: Parse", "jsontest", "parse" },
    { "json: Output", "jsontest", "out" },
    { "json: Tree Parse", "jsontest", "treeparse" },
    { "json: Tree Output", "jsontest", "treeout" },
    { "json: Pull Parse", "jsontest", "pullparse" },
    { "json: Pull Early Stop", "jsontest", "pullearlystop" },
    { "math: PCG Random Integer", "mathtest", "pcgint" },
    { "math: PCG Random Float", "mathtest", "pcgfloat" },
    { "math: PCG Error Condition", "mathtest", "pcgerror" },
    { "math: FP Comparison", "mathtest", "floatcmp" },
    { "fs: Path Matching", "fstest", "pathmatch" },
    { "fs: File Handles", "fstest", "file" },
    { "fs: Directory and search operations", "fstest", "ops" },
    { "vfs: Basic operations", "vfstest", "basic" },
    { "vfs: Write and delete", "vfstest", "write" },
    { "vfs: Layering", "vfstest", "layer" },
    { "vfs: Opaque layer", "vfstest", "opaque" },
    { "vfs: Read-only mount", "vfstest", "readonly" },
    { "vfs: Directory search", "vfstest", "search" },
    { "vfs: Mount and unmount", "vfstest", "mount" },
    { "vfs: Current directory", "vfstest", "curdir" },
    { "vfs: Cache invalidation", "vfstest", "invalidate" },
    { "vfs: Copy-on-write", "vfstest", "cow" },
    { "vfs: Failed copy-on-write", "vfstest", "cowfail" },
    { "vfs: New file layer selection", "vfstest", "newfiles" },
    { "vfs: Rename", "vfstest", "rename" },
    { "vfs: Error paths", "vfstest", "errors" },
    { "vfs: Case-insensitive resolution", "vfstest", "caseinsens" },
    { "vfs: Loopback mount", "vfstest", "loopback" },
    { "vfs: Mixed case sensitivity", "vfstest", "casemix" },
    { "vfs: Mount point entries", "vfstest", "mountents" },
    { "vfs: Cache eviction", "vfstest", "evict" },
    { "vfs: Directory operations", "vfstest", "dirops" },
    { "vfs: Copy", "vfstest", "copy" },
    { "vfs: File I/O", "vfstest", "fileio" },
    { "vfs: NoCache mount", "vfstest", "nocache" },
    { "vfs: Concurrency", "vfstest", "concurrency" },
    { "vfs: OS filesystem provider", "vfstest", "fsprov" },
    { "prqueue: Basic Pointer-Ring Queue", "prqtest", "basic" },
    { "prqueue: Multithreaded Queue", "prqtest", "mt" },
    { "prqueue: Queue Growth", "prqtest", "grow" },
    { "prqueue: Garbage Collection", "prqtest", "gc" },
    { "prqueue: Dynamic MPMC", "prqtest", "mpmc" },
    { "net: Address Parsing", "nettest", "addr" },
    { "netflow: Basic Flow Demux", "nettest", "flow_basic" },
    { "netflow: Handler Resolution", "nettest", "flow_handlers" },
    { "netflow: Close and Teardown", "nettest", "flow_close" },
    { "netflow: Cap Pressure Reclaim", "nettest", "flow_reclaim" },
    { "netflow: Reclaim Idle Threshold", "nettest", "flow_reclaim_idle" },
    { "netflow: Resurrection", "nettest", "flow_resurrect" },
    { "netflow: Socket and Queue Shutdown", "nettest", "flow_shutdown" },
    { "netflow: Requeue Race", "nettest", "flow_race" },
    { "netflow: QUIC Route Hook", "nettest", "quic_route" },
    { "netflow: QUIC Socket", "nettest", "quic_socket" },
    { "netflow: QUIC Flow Admit", "nettest", "quic_admitobj" },
    { "nettimer: Basic Fire", "nettest", "timer_basic" },
    { "nettimer: Cancel Claim", "nettest", "timer_cancel" },
    { "nettimer: Rearm", "nettest", "timer_rearm" },
    { "nettimer: Repeating", "nettest", "timer_repeat" },
    { "nettimer: Flow Ordering", "nettest", "timer_ordering" },
    { "nettimer: Flow Teardown", "nettest", "timer_flowclose" },
    { "netfilter: Stream Passthrough", "nettest", "filter_stream" },
    { "netfilter: Secured Handshake", "nettest", "filter_secured" },
    { "netfilter: Length-2 Chain", "nettest", "filter_chain" },
    { "netfilter: Datagram Round Trip", "nettest", "filter_dgram" },
    { "netfilter: Datagram Flow Chains", "nettest", "filter_dgram_flows" },
    { "netfilter: Teardown", "nettest", "filter_teardown" },
    { "netfilter: Datagram Pool Reference", "nettest", "filter_dgram_poolref" },
#if defined(_PLATFORM_WIN) || defined(_PLATFORM_UNIX)
    { "net: Composed Helpers", "nettest", "helpers" },
    { "net: Per-Datagram IP Information", "nettest", "pktinfo" },
    { "netfilter: Datagram Cold Send", "nettest", "filter_dgram_send" },
    { "netselect: Datagram Loopback", "nettest", "select_udp" },
    { "netselect: Stream Loopback", "nettest", "select_stream" },
    { "netselect: Threaded Datagram Loopback", "nettest", "select_udp_threaded" },
    { "netselect: Threaded Stream Loopback", "nettest", "select_stream_threaded" },
    { "netselect: Stream Send", "nettest", "select_stream_send" },
    { "netselect: Datagram Send", "nettest", "select_udp_send" },
    { "netselect: Stream Backpressure", "nettest", "select_stream_backpressure" },
    { "netselect: Connect", "nettest", "select_connect" },
    { "netselect: Connect DNS", "nettest", "select_connect_dns" },
    { "netselect: Connect Refused", "nettest", "select_connect_refused" },
    { "netselect: Connect Timeout", "nettest", "select_connect_timeout" },
    { "netselect: Accept", "nettest", "select_accept" },
    { "netselect: Accept AutoAccept", "nettest", "select_accept_auto" },
    { "nettimer: Wait Bounding", "nettest", "timer_wait" },
    { "nettimer: Wake While Parked", "nettest", "timer_wake" },
#if defined(_PLATFORM_WIN)
    { "netiocp: Datagram Loopback", "nettest", "iocp_udp" },
    { "netiocp: Stream Loopback", "nettest", "iocp_stream" },
    { "netiocp: Threaded Datagram Loopback", "nettest", "iocp_udp_threaded" },
    { "netiocp: Threaded Stream Loopback", "nettest", "iocp_stream_threaded" },
    { "netiocp: Stream Send", "nettest", "iocp_stream_send" },
    { "netiocp: Datagram Send", "nettest", "iocp_udp_send" },
    { "netiocp: Stream Backpressure", "nettest", "iocp_stream_backpressure" },
    { "netiocp: Connect", "nettest", "iocp_connect" },
    { "netiocp: Connect DNS", "nettest", "iocp_connect_dns" },
    { "netiocp: Connect Refused", "nettest", "iocp_connect_refused" },
    { "netiocp: Connect Timeout", "nettest", "iocp_connect_timeout" },
    { "netiocp: Accept", "nettest", "iocp_accept" },
    { "netiocp: Accept AutoAccept", "nettest", "iocp_accept_auto" },
#endif
#if defined(_PLATFORM_LINUX)
    { "netepoll: Datagram Loopback", "nettest", "epoll_udp" },
    { "netepoll: Stream Loopback", "nettest", "epoll_stream" },
    { "netepoll: Stream Backpressure", "nettest", "epoll_stream_backpressure" },
    { "netepoll: Threaded Datagram Loopback", "nettest", "epoll_udp_threaded" },
    { "netepoll: Threaded Stream Loopback", "nettest", "epoll_stream_threaded" },
    { "netepoll: Connect", "nettest", "epoll_connect" },
    { "netepoll: Connect DNS", "nettest", "epoll_connect_dns" },
    { "netepoll: Connect Refused", "nettest", "epoll_connect_refused" },
    { "netepoll: Connect Timeout", "nettest", "epoll_connect_timeout" },
    { "netepoll: Accept", "nettest", "epoll_accept" },
    { "netepoll: Accept AutoAccept", "nettest", "epoll_accept_auto" },
#endif
#if defined(_PLATFORM_FBSD)
    { "netkqueue: Datagram Loopback", "nettest", "kqueue_udp" },
    { "netkqueue: Stream Loopback", "nettest", "kqueue_stream" },
    { "netkqueue: Stream Backpressure", "nettest", "kqueue_stream_backpressure" },
    { "netkqueue: Threaded Datagram Loopback", "nettest", "kqueue_udp_threaded" },
    { "netkqueue: Threaded Stream Loopback", "nettest", "kqueue_stream_threaded" },
    { "netkqueue: Connect", "nettest", "kqueue_connect" },
    { "netkqueue: Connect DNS", "nettest", "kqueue_connect_dns" },
    { "netkqueue: Connect Refused", "nettest", "kqueue_connect_refused" },
    { "netkqueue: Connect Timeout", "nettest", "kqueue_connect_timeout" },
    { "netkqueue: Accept", "nettest", "kqueue_accept" },
    { "netkqueue: Accept AutoAccept", "nettest", "kqueue_accept_auto" },
#endif
#endif
#if defined(CX_TLS_TESTS)
    { "tls13: HKDF-Expand-Label", "tls13test", "expandlabel" },
    { "tls13: Transcript Hash", "tls13test", "transcript" },
    { "tls13: Key Schedule", "tls13test", "schedule" },
    { "tls13: Key Schedule 0-RTT", "tls13test", "schedule_early" },
    { "tls13: ECDHE Known Answer", "tls13test", "ecdhe" },
    { "tls13: ECDHE Generated Keys", "tls13test", "ecdhe_generate" },
    { "tls13: Hello Codec", "tls13test", "hello" },
    { "tls13: Malformed Hello", "tls13test", "hello_malformed" },
    { "tlsquic: Handshake", "tlsquictest", "handshake" },
    { "tlsquic: Message Reassembly", "tlsquictest", "reassembly" },
    { "tlsquic: HelloRetryRequest", "tlsquictest", "retry" },
    { "tlsquic: AES-256-GCM Suite", "tlsquictest", "suite_aes256" },
    { "tlsquic: ChaCha20-Poly1305 Suite", "tlsquictest", "suite_chacha" },
    { "tlsquic: Mutual Authentication", "tlsquictest", "mutual" },
    { "tlsquic: Missing Client Certificate", "tlsquictest", "mutual_missing" },
    { "tlsquic: Untrusted Certificate", "tlsquictest", "untrusted" },
    { "tlsquic: Wrong Hostname", "tlsquictest", "wrongname" },
    { "tlsquic: ALPN Mismatch", "tlsquictest", "alpn_mismatch" },
    { "tlsquic: Tampered Finished", "tlsquictest", "tampered" },
    { "tlsquic: Session Resumption", "tlsquictest", "resume" },
    { "tlsquic: Rejected Ticket", "tlsquictest", "resume_rejected" },
    { "tlsquic: Corrupted PSK Binder", "tlsquictest", "resume_badbinder" },
    { "tlsquic: Early Data", "tlsquictest", "early" },
    { "tlsquic: Early Data Refused", "tlsquictest", "early_refused" },
    { "tlsquic: Early Data After Retry", "tlsquictest", "early_hrr" },
    { "tlsquic: EndOfEarlyData Refused", "tlsquictest", "early_eoed" },
    { "tlsquic: Secret Ordering", "tlsquictest", "key_order" },
    { "tlsquic: Compatibility Mode Refused", "tlsquictest", "compat_mode" },
    { "tlsquic: Missing Transport Parameters", "tlsquictest", "no_transport_params" },
    { "tlsquic: Missing Signature Algorithms", "tlsquictest", "no_sigalgs" },
    { "tlsquic: CertificateVerify Content", "tlsquictest", "certverify_content" },
    { "tlsquic: Misuse", "tlsquictest", "misuse" },
#endif
#if defined(CX_QUIC_TESTS)
    { "quic: Varints", "quictest", "varint" },
    { "quic: Packet Numbers", "quictest", "pn" },
    { "quic: Packet Headers", "quictest", "header" },
    { "quic: Malformed Headers", "quictest", "header_malformed" },
    { "quic: Frames", "quictest", "frames" },
    { "quic: ACK Ranges", "quictest", "ack" },
    { "quic: Malformed Frames", "quictest", "frames_malformed" },
    { "quic: Initial Keys", "quictest", "initial_keys" },
    { "quic: Header Protection", "quictest", "hpmask" },
    { "quic: Client Initial Packet", "quictest", "initial_client" },
    { "quic: Server Initial Packet", "quictest", "initial_server" },
    { "quic: ChaCha20 Short Packet", "quictest", "chacha" },
    { "quic: Retry Integrity Tag", "quictest", "retry" },
    { "quicrecov: Send Buffer", "quicrecovtest", "sendbuf" },
    { "quicrecov: Send Buffer Growth", "quicrecovtest", "sendbuf_many" },
    { "quicrecov: Round Trip Estimation", "quicrecovtest", "rtt" },
    { "quicrecov: Round Trip Samples", "quicrecovtest", "rtt_noelicit" },
    { "quicrecov: Loss By Packet Threshold", "quicrecovtest", "loss_packet" },
    { "quicrecov: Loss By Time Threshold", "quicrecovtest", "loss_time" },
    { "quicrecov: Reordering", "quicrecovtest", "reorder" },
    { "quicrecov: Loss Beyond The Acknowledged", "quicrecovtest", "loss_beyond" },
    { "quicrecov: Sent Packet Ring", "quicrecovtest", "ring" },
    { "quicrecov: Probe Timeout", "quicrecovtest", "pto" },
    { "quicrecov: Probe Timeout Space", "quicrecovtest", "pto_space" },
    { "quicrecov: Probe Timeout Deadlock", "quicrecovtest", "pto_deadlock" },
    { "quicrecov: Congestion Window", "quicrecovtest", "cwnd" },
    { "quicrecov: Congestion Window After Loss", "quicrecovtest", "cwnd_loss" },
    { "quicrecov: Congestion Window Floor", "quicrecovtest", "cwnd_floor" },
    { "quicrecov: Persistent Congestion", "quicrecovtest", "persistent" },
    { "quicrecov: Brief Congestion", "quicrecovtest", "persistent_short" },
    { "quicrecov: Congestion Recovery Period", "quicrecovtest", "cwnd_recovery" },
    { "quicrecov: Interrupted Congestion", "quicrecovtest", "persistent_broken" },
    { "quicrecov: Congestion Without A Measurement", "quicrecovtest", "persistent_nortt" },
    { "quicrecov: Congestion Before A Measurement", "quicrecovtest", "persistent_firstsample" },
    { "quicrecov: Congestion Across Two Timers", "quicrecovtest", "persistent_split" },
    { "quicrecov: Application Limited", "quicrecovtest", "applimited" },
    { "quicrecov: Discarded Number Space", "quicrecovtest", "discard" },
    { "quicrecov: Pacing", "quicrecovtest", "pacing" },

    { "quicstream: Stream Identifiers", "quicstreamtest", "ids" },
    { "quicstream: Opening Streams", "quicstreamtest", "open" },
    { "quicstream: Stream Count Limit", "quicstreamtest", "openlimit" },
    { "quicstream: Sending Data", "quicstreamtest", "send" },
    { "quicstream: Bulk Transfer", "quicstreamtest", "bulk" },
    { "quicstream: Unidirectional Streams", "quicstreamtest", "uni" },
    { "quicstream: Interleaved Streams", "quicstreamtest", "interleave" },
    { "quicstream: Stream Fairness", "quicstreamtest", "fairness" },
    { "quicstream: Out Of Order Arrival", "quicstreamtest", "reorder" },
    { "quicstream: Stream Flow Control", "quicstreamtest", "flow_stream" },
    { "quicstream: Connection Flow Control", "quicstreamtest", "flow_conn" },
    { "quicstream: Stream Window Overrun", "quicstreamtest", "flow_violate_stream" },
    { "quicstream: Connection Window Overrun", "quicstreamtest", "flow_violate_conn" },
    { "quicstream: Window Updates", "quicstreamtest", "window" },
    { "quicstream: Stream Data Retransmission", "quicstreamtest", "retransmit" },
    { "quicstream: Window Update Retransmission", "quicstreamtest", "retransmit_window" },
    { "quicstream: Send Range Limit", "quicstreamtest", "sendchunks" },
    { "quicstream: Late Finish", "quicstreamtest", "finlate" },
    { "quicstream: End Of Stream Retransmission", "quicstreamtest", "retransmit_fin" },
    { "quicstream: Resetting A Stream", "quicstreamtest", "reset" },
    { "quicstream: Reset Flow Control Credit", "quicstreamtest", "reset_credit" },
    { "quicstream: Stop Sending", "quicstreamtest", "stop" },
    { "quicstream: Reset Closes The Stream", "quicstreamtest", "reset_close" },
    { "quicstream: Reading A Stream In Pieces", "quicstreamtest", "partial_read" },
    { "quicstream: Resetting Twice", "quicstreamtest", "reset_twice" },
    { "quicstream: Ending A Stream After A Reset", "quicstreamtest", "finish_after_reset" },
    { "quicstream: Stop Sending After The End", "quicstreamtest", "stop_after_end" },
    { "quicstream: Duplicate Reset", "quicstreamtest", "reset_duplicate" },
    { "quicstream: Reset Before Anything Was Sent", "quicstreamtest", "reset_pending" },
    { "quicstream: Reset Retransmission", "quicstreamtest", "retransmit_reset" },
    { "quicstream: Connection Window Retransmission", "quicstreamtest", "retransmit_maxdata" },
    { "quicstream: Stale Blocked Complaint", "quicstreamtest", "blocked_stale" },
    { "quicstream: Stale Connection Blocked Complaint", "quicstreamtest", "blocked_stale_conn" },
    { "quicstream: Stale Stream Count Complaint", "quicstreamtest", "blocked_stale_streams" },
    { "quicstream: Reset Drops The Blocked Complaint", "quicstreamtest", "reset_drops_blocked" },
    { "quicstream: No Window For A Finished Stream", "quicstreamtest", "window_ended" },
    { "quicstream: End Acknowledged Before The Data", "quicstreamtest", "fin_outstanding" },
    { "quicstream: Data Past The Final Size", "quicstreamtest", "final_size" },
    { "quicstream: Final Size Changed", "quicstreamtest", "final_size_moved" },
    { "quicstream: Reset Below The Final Size", "quicstreamtest", "final_size_reset" },
    { "quicstream: Reset Against A Known Final Size", "quicstreamtest", "final_size_moved_reset" },
    { "quicstream: Stream Id Over The Limit", "quicstreamtest", "limit" },
    { "quicstream: Implicitly Opened Streams", "quicstreamtest", "implicit" },
    { "quicstream: Frames For The Wrong Half", "quicstreamtest", "state_errors" },
    { "quicstream: Refusing A Stream", "quicstreamtest", "refuse" },
    { "quicstream: Frames For A Finished Stream", "quicstreamtest", "closed_ignored" },
    { "quicstream: Raising The Stream Limit", "quicstreamtest", "maxstreams" },
    { "quicstream: Bidirectional Window Parameters", "quicstreamtest", "bidi_params" },
    { "quicconn: Transport Parameters", "quicconntest", "params" },
    { "quicconn: Malformed Transport Parameters", "quicconntest", "params_malformed" },
    { "quicconn: Stream Reassembly", "quicconntest", "reasm" },
    { "quicconn: Acknowledgement Ranges", "quicconntest", "ackset" },
    { "quicconn: Address Validation Tokens", "quicconntest", "token" },
    { "quicconn: Handshake", "quicconntest", "handshake" },
    { "quicconn: 1-RTT Frames", "quicconntest", "onertt" },
    { "quicconn: Key Update", "quicconntest", "keyupdate" },
    { "quicconn: Initial Padding", "quicconntest", "padding" },
    { "quicconn: Server Initial Padding", "quicconntest", "srvpad" },
    { "quicconn: Duplicate Packet", "quicconntest", "dup_packet" },
    { "quicconn: Retry", "quicconntest", "retry" },
    { "quicconn: Forged Retry", "quicconntest", "retry_forged" },
    { "quicconn: Transport Parameter Mismatch", "quicconntest", "tp_mismatch" },
    { "quicconn: No Frames", "quicconntest", "no_frames" },
    { "quicconn: Unsent Acknowledgement", "quicconntest", "bad_ack" },
    { "quicconn: Connection ID Limit", "quicconntest", "cid_limit" },
    { "quicconn: Malformed Connection IDs", "quicconntest", "cid_bad" },
    { "quicconn: Version Negotiation", "quicconntest", "versionneg" },
    { "quicconn: Connection Close", "quicconntest", "close" },
    { "quicconn: Close Encryption Level", "quicconntest", "close_level" },
    { "quicconn: Malformed Frame", "quicconntest", "bad_frame" },
    { "quicconn: Stream Frame Refused", "quicconntest", "stream_refused" },
    { "quicconn: Frame At The Wrong Level", "quicconntest", "frame_level" },
    { "quicconn: Frames From The Wrong Role", "quicconntest", "role_frames" },
    { "quicconn: Idle Timeout", "quicconntest", "idle" },
    { "quicconn: Stateless Reset", "quicconntest", "statelessreset" },
    { "quicconn: Connection IDs", "quicconntest", "cids" },
    { "quicconn: Path Validation", "quicconntest", "path" },
    { "quicconn: Replaced Path Challenge", "quicconntest", "path_replace" },
    { "quicconn: Amplification Limit", "quicconntest", "amplification" },
    { "quicconn: Lost Initial Packet", "quicconntest", "loss_initial" },
    { "quicconn: Lost Handshake Flight", "quicconntest", "loss_flight" },
    { "quicconn: Lost Handshake Bytes", "quicconntest", "loss_crypto" },
    { "quicconn: Lost Control Frame", "quicconntest", "loss_control" },
    { "quicconn: Congestion Control", "quicconntest", "congestion" },
    { "quicconn: Congestion Window Limit", "quicconntest", "congestion_limit" },
    { "quicconn: Congestion Window Sliver", "quicconntest", "congestion_sliver" },
    { "quicconn: ECN Marking", "quicconntest", "ecn" },
    { "quicconn: ECN Stripped By Path", "quicconntest", "ecn_stripped" },
    { "quicconn: ECN Congestion Response", "quicconntest", "ecn_congestion" },
    { "quicconn: Path MTU Discovery", "quicconntest", "pmtu" },
    { "quicconn: Path MTU At The Floor", "quicconntest", "pmtu_floor" },
    { "quicconn: Peer Migration", "quicconntest", "migrate" },
    { "quicconn: Probing Packet Does Not Migrate", "quicconntest", "migrate_probing" },
    { "quicconn: Reordered Packet Does Not Migrate", "quicconntest", "migrate_reorder" },
    { "quicconn: Migration Fallback", "quicconntest", "migrate_fallback" },
    { "quicconn: Migration Resets Path State", "quicconntest", "migrate_resets" },
    { "quicconn: Migration Before Handshake Confirmed", "quicconntest", "migrate_early" },
    { "quicconn: Self-Initiated Migration Fails", "quicconntest", "migrate_self_fails" },
    { "quicconn: Path Response Address", "quicconntest", "path_response_addr" },
    { "quicconn: ECN Partially Stripped", "quicconntest", "ecn_partial" },
    { "quicconn: ECN Counts That Go Backwards", "quicconntest", "ecn_lying" },
    { "quicconn: Pacing", "quicconntest", "pacing" },
    { "quicconn: Acknowledgement Delay", "quicconntest", "ack_delay" },
    { "quicconn: Early Data", "quicconntest", "early" },
    { "quicconn: Early Data Rejected", "quicconntest", "early_rejected" },
    { "quicconn: Frame Forbidden In 0-RTT", "quicconntest", "early_badframe" },
    { "quicconn: Resumption Without Early Data", "quicconntest", "early_off" },
    { "quicconn: Stream Round Trip", "quicconntest", "stream_echo" },
    { "quicconn: Stream Bulk Transfer", "quicconntest", "stream_bulk" },
    { "quicconn: Stream Transfer Under Loss", "quicconntest", "stream_loss" },
    { "quicconn: Stream Data Lost In Flight", "quicconntest", "stream_loss_data" },
    { "quicconn: Stream Reset", "quicconntest", "stream_reset" },
    { "quicconn: Stream Reset Lost In Flight", "quicconntest", "stream_reset_loss" },
    { "quicconn: Stream Tail Loss", "quicconntest", "stream_tail_loss" },
    { "quicconn: Stream Frame For The Wrong Half", "quicconntest", "stream_violation" },
#if defined(_PLATFORM_WIN) || defined(_PLATFORM_UNIX)
    { "quicnet: Handshake", "quicnettest", "handshake" },
    { "quicnet: Stream Echo", "quicnettest", "echo" },
    { "quicnet: Concurrent Streams", "quicnettest", "streams" },
    { "quicnet: Unidirectional Stream", "quicnettest", "uni" },
    { "quicnet: Streams From Both Ends", "quicnettest", "bothways" },
    { "quicnet: Finishing A Stream", "quicnettest", "finish" },
    { "quicnet: Closing A Stream Flow", "quicnettest", "flowclose" },
    { "quicnet: Resetting A Stream", "quicnettest", "reset" },
    { "quicnet: Stop Sending", "quicnettest", "stopsending" },
    { "quicnet: Bulk Transfer", "quicnettest", "bulk" },
    { "quicnet: Send Wakeup", "quicnettest", "sendwakeup" },
    { "quicnet: Echo Streams", "quicnettest", "echostreams" },
    { "quicnet: Receive Backpressure", "quicnettest", "backpressure" },
    { "quicnet: Stream Limit", "quicnettest", "streamlimit" },
    { "quicnet: Connection Close", "quicnettest", "close" },
    { "quicnet: Listener Close", "quicnettest", "listener_close" },
    { "quicnet: Retry", "quicnettest", "retry" },
    { "quicnet: No Listener", "quicnettest", "nolistener" },
    { "quicnet: ALPN", "quicnettest", "alpn" },
    { "quicnet: Two Clients", "quicnettest", "two_clients" },
    { "quicnet: Repeated Initial", "quicnettest", "dup_initial" },
    { "quicnet: Short Initial", "quicnettest", "short_initial" },
    { "quicnet: ECN", "quicnettest", "ecn" },
    { "quicnet: Path MTU Discovery", "quicnettest", "pathmtu" },
    { "quicnet: Connection Migration", "quicnettest", "migrate" },
    { "quicnet: Early Data", "quicnettest", "earlydata" },
#endif
#endif
#if defined(CX_TLS_TESTS) && (defined(_PLATFORM_WIN) || defined(_PLATFORM_UNIX))
    { "tls: Handshake", "tlstest", "handshake" },
    { "tls: Wire Is Encrypted", "tlstest", "wire" },
    { "tls: Certificate Verification", "tlstest", "verify" },
    { "tls: Hostname Verification", "tlstest", "hostname" },
    { "tls: Bulk Transfer", "tlstest", "large" },
    { "tls: STARTTLS Upgrade", "tlstest", "starttls" },
    { "tls: ALPN", "tlstest", "alpn" },
    { "tls: Mutual TLS", "tlstest", "mtls" },
    { "tls: Certificate Rotation", "tlstest", "rotate" },
    { "tls: Orderly Shutdown", "tlstest", "shutdown" },
    { "tls: Session Resumption", "tlstest", "resume" },
    { "tls: Post-Handshake Tickets", "tlstest", "tickets" },
    { "tls: Unusable Config Fails Closed", "tlstest", "failclosed" },
#endif
#if defined(CX_HTTP_TESTS) && (defined(_PLATFORM_WIN) || defined(_PLATFORM_UNIX))
    { "http: URL Parsing", "httptest", "url" },
    { "http: URL Composition", "httptest", "urlformat" },
    { "http: URL Reference Resolution", "httptest", "urlresolve" },
    { "http: Percent Coding", "httptest", "urlcodec" },
    { "http: Query Strings", "httptest", "query" },
    { "http: Header List", "httptest", "headers" },
    { "http: Header Tokens", "httptest", "headertoken" },
    { "http: Header Formatting", "httptest", "headerformat" },
    { "http: HTTP-date", "httptest", "date" },
    { "http: Response Parsing", "httptest", "parseresp" },
    { "http: Chunked Decoding", "httptest", "parsechunked" },
    { "http: Body Framing", "httptest", "parseframing" },
    { "http: Interim Responses", "httptest", "parseinterim" },
    { "http: Malformed Messages", "httptest", "parsereject" },
    { "http: Parser Limits", "httptest", "parselimits" },
    { "http: Request Parsing", "httptest", "parsereq" },
    { "http: Pipelined Reuse", "httptest", "parsereuse" },
    { "http: Chunked Encoding", "httptest", "chunkwrite" },
    { "http: Connection Exchange", "httptest", "conn" },
    { "http: Request Body and Split Response", "httptest", "connbody" },
    { "http: Interim Response On Connection", "httptest", "conninterim" },
    { "http: Connection Reuse", "httptest", "connreuse" },
    { "http: Connection Protocol Error", "httptest", "connerror" },
    { "http: Connection Truncation", "httptest", "conntruncated" },
    { "http: Cookie Jar", "httptest", "cookiejar" },
    { "http: Form Bodies", "httptest", "form" },
    { "http: Client Request", "httptest", "clientget" },
    { "http: Client Redirect", "httptest", "clientredirect" },
    { "http: Client Temporary Redirect", "httptest", "clienttempredir" },
    { "http: Client Buffer Body", "httptest", "clientbodybuf" },
    { "http: Client Streamed Body", "httptest", "clientstreambody" },
    { "http: Client Progress", "httptest", "clientprogress" },
    { "http: Client Progress Chunked", "httptest", "clientprogchunk" },
    { "http: Client Redirect Limit", "httptest", "clientredirloop" },
    { "http: Client See Other", "httptest", "clientseeother" },
    { "http: Client Connection Pool", "httptest", "clientpool" },
    { "http: Client Cookies", "httptest", "clientcookie" },
    { "http: Client Response Sink", "httptest", "clientsink" },
    { "http: Client Connection Refused", "httptest", "clientrefused" },
    { "http: Client Response Timeout", "httptest", "clienttimeout" },
    { "http: Client Cancel", "httptest", "clientcancel" },
    { "http: Client Cancel While Dialing", "httptest", "clientcancelearly" },
    { "http: Client Cancel After Completion", "httptest", "clientcanceldone" },
    { "http: Client Cancel Evicts Connection", "httptest", "clientcancelpool" },
    { "http: Connection Cancel", "httptest", "conncancel" },
    { "http: Server GET", "httptest", "srvget" },
    { "http: Server Progress", "httptest", "srvprogress" },
    { "http: Server POST Body", "httptest", "srvpost" },
    { "http: Server Chunked Request", "httptest", "srvchunkedreq" },
    { "http: Server Keep-Alive", "httptest", "srvkeepalive" },
    { "http: Server Connection Close", "httptest", "srvclose" },
    { "http: Server Serialized Requests", "httptest", "srvserialized" },
    { "http: Server Bad Request", "httptest", "srvbadrequest" },
    { "http: Server Bad Target", "httptest", "srvbadtarget" },
    { "http: Server Head Too Large", "httptest", "srvtoolarge" },
    { "http: Server Head Read Timeout", "httptest", "srvheadreadtimeout" },
    { "http: Server HEAD Method", "httptest", "srvhead" },
    { "http: Server Bodiless Status", "httptest", "srvnobody" },
    { "http: Server Held Request", "httptest", "srvheld" },
    { "http: Server Late Response", "httptest", "srvlateresponse" },
    { "http: Server Attached Listener", "httptest", "srvattach" },
    { "http: Server Body Sink", "httptest", "srvsink" },
    { "http: Server Chunked Body Sink", "httptest", "srvsinkchunked" },
    { "http: Server Body Data Handler", "httptest", "srvdata" },
    { "http: Server Streamed Response", "httptest", "srvstreamresp" },
    { "http: Server Chunked Response", "httptest", "srvchunkedresp" },
    { "http: Server Push Response", "httptest", "srvpushresp" },
    { "http: Server Expect Continue", "httptest", "srvcontinue" },
    { "http: Server Manual Continue", "httptest", "srvcontinuemanual" },
    { "http: Server Bad Expect", "httptest", "srvexpectbad" },
    { "http: Server Deferred Response", "httptest", "srvdeferred" },
    { "http: Server TLS", "httptest", "srvtls" },
    { "http: Client TLS ALPN", "httptest", "clienttlsalpn" },
    { "http: Server Client Round Trip", "httptest", "srvroundtrip" },
    { "http: Multipart File Upload", "httptest", "multipartfile" },
    { "http: Multipart Chunked Upload", "httptest", "multipartchunk" },
#endif
    { "taskqueue: Tasks", "tqtest", "task" },
    { "taskqueue: Failed Tasks", "tqtest", "failure" },
    { "taskqueue: Concurrency (in-worker)", "tqtest", "concurrency_inworker" },
    { "taskqueue: Concurrency (dedicated)", "tqtest", "concurrency_dedicated" },
    { "taskqueue: Call", "tqtest", "call" },
    { "taskqueue: Scheduled Tasks", "tqtest", "sched" },
    { "taskqueue: Monitor (in-worker)", "tqtest", "monitor_inworker" },
    { "taskqueue: Monitor (dedicated)", "tqtest", "monitor_dedicated" },
    { "taskqueue: Dependencies", "tqtest", "depend" },
    { "taskqueue: Require Mutex", "tqtest", "reqmutex" },
    { "taskqueue: Require FIFO", "tqtest", "reqfifo" },
    { "taskqueue: Require LIFO", "tqtest", "reqlifo" },
    { "taskqueue: Require Gate", "tqtest", "reqgate" },
    { "taskqueue: Dependency Timeout", "tqtest", "timeout" },
    { "taskqueue: Manual", "tqtest", "manual" },
    { "taskqueue: Oneshot", "tqtest", "oneshot" },
    { "taskqueue: Multiphase", "tqtest", "multiphase" },
    { "cpp: SArray", "cpptest", "sarray" },
    { "cpp: Hashtable", "cpptest", "hashtable" },
    { "cpp: stype", "cpptest", "stype" },
    { "cpp: stvar", "cpptest", "stvar" },
    { "cpp: Object", "cpptest", "object" },
    { 0 }
};

extern int main(int argc, const char *argv[]);

int alltests(int argc, const char *argv[])
{
    const testspec *s;
    int ntests = 0;

    for (s = &tests[0]; s->descr; s++) {
        ntests++;
    }

    if (ntests == 0) {
        puts("No tests to run!");
        return 1;
    }

    int npassed = 0;
    int64 totalstart = clockTimer();

    // Trailing flags on alltests' own argv (e.g. "-log=Warn") are forwarded to every
    // sub-invocation, so a manual "alltests -log=Warn" run gets the same per-test verbosity as
    // CX_TEST_LOGLEVEL gives a bulk ctest run.
    const char *fake_argv[2 + 16];
    int nflags = 0;
    for (int i = 1; i < argc && nflags < 16; i++)
        fake_argv[3 + nflags++] = argv[i];

    fake_argv[0] = argv[0];

    puts("Running tests...");

    for (int i = 0; i < ntests; i++)
    {
        int64 tstart = clockTimer();
        printf("%4d/%d: %s ", i + 1, ntests, tests[i].descr);
        int ndots = 40 - (int)strlen(tests[i].descr);
        for (int j = 0; j < ndots; j++)
            putchar('.');
        fflush(stdout);

        logRestart();   // the previous test may have shut down the logging system
        fake_argv[1] = tests[i].module;
        fake_argv[2] = tests[i].test;
        bool res = main(3 + nflags, fake_argv);
        int64 tend = clockTimer();

        printf("    %s    %4d msec\n",
                res ? "Failed" : "Passed", (int)timeToMsec(tend - tstart));
        if (!res)
            npassed++;
        xaFlush();
    }

    int64 totalend = clockTimer();
    printf("\n%d%% tests passed, %d tests failed out of %d, total elapsed %d msec\n",
            npassed * 100 / ntests, ntests - npassed, ntests,
            (int)timeToMsec(totalend - totalstart));

    return ntests - npassed;
}
