/// @file
/// @note This file is automatically generated from @link /home/number6/cx/cxautogen/cx/fs/fileobj.cxh @endlink
/// @addtogroup fs_file
/// @{

#pragma once
// This header file is auto-generated!
// Do not make changes to this file or they will be overwritten.
// clang-format off
#include <cx/obj.h>
#include <cx/struct.h>
#include <cx/fs/fs.h>

CX_C_BEGIN

typedef struct File File;
typedef struct File_WeakRef File_WeakRef;
saDeclarePtr(File);
saDeclarePtr(File_WeakRef);
#define _sti_File _sti_object
#define SType_File File*
#define STStorageType_File File*
#define STypeArg_File(type, val) stgeneric(object, (ObjInst*)objInstCheckClass(File, val))
#define STypeArgPtr_File(type, val) (stgeneric*)objInstCheckClassPtr(File, val)
#define STypeCheckedArg_File(type, val)    stType(type), stArg(type, val)
#define STypeCheckedPtrArg_File(type, val) stType(type), stArgPtr(type, val)



typedef struct File_ClassIf {
    ObjIface* _implements;
    ObjIface* _parent;
    size_t _size;

    bool (*close)(_In_ void* self);
    bool (*read)(_In_ void* self, _Out_writes_bytes_to_(sz, *bytesread) void* buf, size_t sz, _Out_ _Deref_out_range_(0, sz) size_t* bytesread);
    bool (*write)(_In_ void* self, _In_reads_bytes_(sz) const void* buf, size_t sz, _Out_opt_ _Deref_out_range_(0, sz) size_t* byteswritten);
    int64 (*tell)(_In_ void* self);
    int64 (*seek)(_In_ void* self, int64 off, FSSeekType seektype);
    bool (*flush)(_In_ void* self);
} File_ClassIf;
extern File_ClassIf File_ClassIf_tmpl;

/// An open file
/// 
/// Every open file is a File, whichever layer opened it: fsOpen() hands back one backed by an
/// OS file handle, and vfsOpen() one backed by a VFS provider. Code that only reads and writes
/// can take a File* and work with either.
/// 
/// A File is reference counted. fileClose() closes the file but keeps the handle alive;
/// objRelease() drops a reference and closes the file if it was the last one.
/// 
/// A file handle is single-owner: one thread at a time, like a C FILE*. Two threads may use two
/// handles on the same file, but they must not share one handle.
typedef struct File {
    union {
        File_ClassIf* _;
        void* _is_File;
        void* _is_ObjInst;
    };
    ObjClassInfo* _clsinfo;
    atomic(uintptr) _ref;
    atomic(ptr) _weakref;

} File;
extern ObjClassInfo File_clsinfo;
#define File(inst) objInstCheckClass(File, inst)
#define FileNone ((File*)NULL)

typedef struct File_WeakRef {
    union {
        ObjInst* _inst;
        void* _is_File_WeakRef;
        void* _is_ObjInst_WeakRef;
    };
    atomic(uintptr) _ref;
    RWLock _lock;
} File_WeakRef;
#define File_WeakRef(inst) objWeakRefCheckClass(File, inst)

bool File_writeString(_In_ File* self, _In_opt_ strref str, _Out_opt_ size_t* byteswritten);
/// bool fileWriteString(File* self, strref str, size_t* byteswritten);
///
/// Writes the contents of a string to the file
/// 
/// The string is written as-is, with no line ending added.
/// 
/// @param str String to write
/// @param byteswritten Receives the number of bytes written, or NULL
/// @return true if the write succeeded, false on an I/O error
#define fileWriteString(self, str, byteswritten) File_writeString(File(self), str, byteswritten)

/// bool fileClose(File* self);
///
/// Closes a file, keeping the handle alive
/// 
/// Flushes pending writes and closes the underlying handle. The File itself stays valid
/// until the last reference is released; further reads and writes fail. Closing an already
/// closed file is harmless.
/// 
/// Use this when more than one owner holds the handle, and have each of them call
/// objRelease() when it is done. A single owner can use fsClose() or vfsClose() instead,
/// which close and release in one step.
/// 
/// @return true if successful, false if an error occurred while flushing or closing, or if
/// self was NULL
#define fileClose(self) ((self) ? ((self)->_->close(File(self))) : false)
/// bool fileRead(File* self, void* buf, size_t sz, size_t* bytesread);
///
/// Reads data from the file
/// 
/// Reads up to sz bytes from the current position into buf and advances the position by the
/// number of bytes actually read. Reading less than requested is not an error; it means the
/// end of the file was reached.
/// 
/// @param buf Buffer to receive the data (must be at least sz bytes)
/// @param sz Maximum number of bytes to read
/// @param bytesread Receives the number of bytes read (0 at end of file)
/// @return true if the read succeeded, false on an I/O error (bytesread is set to 0)
#define fileRead(self, buf, sz, bytesread) ((self) ? ((self)->_->read(File(self), buf, sz, bytesread)) : false)
/// bool fileWrite(File* self, const void* buf, size_t sz, size_t* byteswritten);
///
/// Writes data to the file
/// 
/// Writes sz bytes from buf at the current position and advances the position by the number
/// of bytes written. Most of the time everything is written or the call fails, but a short
/// write is possible on some filesystems, so check byteswritten when it matters.
/// 
/// @param buf Buffer containing the data to write
/// @param sz Number of bytes to write
/// @param byteswritten Receives the number of bytes written, or NULL
/// @return true if the write succeeded, false on an I/O error
#define fileWrite(self, buf, sz, byteswritten) ((self) ? ((self)->_->write(File(self), buf, sz, byteswritten)) : false)
/// int64 fileTell(File* self);
///
/// Gets the current position in the file
/// 
/// @return Current position in bytes from the start of the file, -1 on error
#define fileTell(self) (self)->_->tell(File(self))
/// int64 fileSeek(File* self, int64 off, FSSeekType seektype);
///
/// Changes the current position in the file
/// 
/// @param off Offset in bytes, which may be negative for FS_Cur and FS_End
/// @param seektype Where to measure from: FS_Set (start), FS_Cur (current), FS_End (end)
/// @return New position in bytes from the start of the file, -1 on error
#define fileSeek(self, off, seektype) ((self) ? ((self)->_->seek(File(self), off, seektype)) : -1)
/// bool fileFlush(File* self);
///
/// Flushes buffered writes to storage
/// 
/// Forces buffered data out to the storage device. This is slow, so only do it when
/// durability matters right now; closing the file flushes it anyway.
/// 
/// @return true if successful, false on error
#define fileFlush(self) ((self) ? ((self)->_->flush(File(self))) : false)

CX_C_END
/// @}
