/// @file hostid.h
/// @brief Stable host identification system
///
/// @defgroup sys_hostid Host ID
/// @ingroup sys
/// @{
///
/// Provides a stable, privacy-preserving host identifier that remains consistent across
/// application runs on the same machine. The ID is generated by hashing platform-specific
/// system identifiers (such as machine IDs, BIOS UUIDs, or configuration files) to create
/// a 256-bit unique identifier.
///
/// The host ID is computed once per application run and cached. The implementation attempts
/// multiple platform-specific identification methods in order of reliability:
/// - **Windows**: BIOS UUID, machine registry keys, CryptoAPI MachineGUID, or computer name
/// - **Unix/Linux**: Machine-wide hostid file, per-user entropy file, or computer name
///
/// The hashing approach ensures end-user privacy while maintaining stability.
///
/// Example:
/// @code
///   HostID hid;
///   hostId(&hid);
///   // hid.id contains 256-bit unique identifier
///   // hid.source indicates which platform method was used
/// @endcode

#pragma once

#include <cx/cx.h>

/// Host identification information
typedef struct HostID {
    uint64 id[4];       ///< 256-bit unique identifier (SHA256 hash)
    int32 source;       ///< Platform-specific source indicator (see platform headers)
} HostID;

/// void hostId(HostID *id)
///
/// Retrieves the stable host identifier for the current machine.
///
/// This function computes the host ID once on first call and caches it for subsequent calls.
/// The identifier is stable across application runs on the same host but may change if
/// underlying system identifiers change (e.g., hardware replacement, OS reinstall).
///
/// @param id Output parameter that receives the host identification
CX_C void hostId(_Out_ HostID *id);

/// @}
